# Indexing

In [9]:
import numpy as np

a = ['a', 'b', 'c', 'd', 'e']

print('a[:1] ', a[:1])
print('a[0] ', a[0])
print('a[0:2] ', a[0:2])
print('a[:-1] ', a[:-1])
print('a[:-2] ', a[:-2])

a[:1]  ['a']
a[0]  a
a[0:2]  ['a', 'b']
a[:-1]  ['a', 'b', 'c', 'd']
a[:-2]  ['a', 'b', 'c']


# Slicing

In [42]:
import numpy as np

x = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

print('prints complete array : \n', x, '\n') # prints complete array
print('prints 0th row : ', x[0], '\n') # prints 0th row
print('prints 1st row less than 1 index elements : ', x[1, :3], '\n') # prints 1st row less than 1 index elements
print('print 0th row (:1 means < 1) : ', x[:1], '\n') # print 0th row (:1 means < 1)
print('print row with index < 1 and elements of row where index is >= 1 :', x[:1, 1:], '\n') # print row with index < 1 and elements of row where index is >= 1
print('print row with index < 1 and elements of row where index is >= 1 :', x[1:, 1:], '\n') # print row with index > 1 and elements of row where index is >= 1
print('print from row 1', x[1:], '\n')
print('print from row 2', x[2:], '\n')
print('print without 1st row and col', x[1:, 1:], '\n')

prints complete array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

prints 0th row :  [1 2 3] 

prints 1st row less than 1 index elements :  [4 5 6] 

print 0th row (:1 means < 1) :  [[1 2 3]] 

print row with index < 1 and elements of row where index is >= 1 : [[2 3]] 

print row with index < 1 and elements of row where index is >= 1 : [[5 6]
 [8 9]] 

print from row 1 [[4 5 6]
 [7 8 9]] 

print from row 2 [[7 8 9]] 

print without 1st row and col [[5 6]
 [8 9]] 



# Numpy Vs List

## Advantages of Numpy over List

In [45]:
# numpy vs list: memory

import sys

# define a list
l = range(1000)
print("memory size taken by list : ", sys.getsizeof(1)*len(l))

# define a numpy array
a = np.arange(1000)
print("memory size taken by numpy array : ", a.size*a.itemsize)

memory size taken by list :  28000
memory size taken by numpy array :  8000


In [51]:
# numpy vs list: speed

import time

def using_list():
    t1 = time.time()
    x = range(10000)
    y = range(10000)
    z = [x[i]+y[i] for i in range(len(x))]
    return time.time() - t1

def using_numpy():
    t1 = time.time()
    x = np.arange(10000)
    y = np.arange(10000)
    z = x+y
    return time.time() - t1

list_time = using_list()
numpy_time = using_numpy()

print('list_time ', list_time, '\n')
print('numpy_time ', numpy_time, '\n')

list_time  0.0029828548431396484 

numpy_time  0.0004487037658691406 

