In [1]:
# 1 dimensional array

import numpy as np

arr = np.array([1, 2, 3])

print(arr)

[1 2 3]


In [2]:
import sys
print(sys.executable)

/opt/homebrew/Cellar/jupyterlab/4.5.7_2/libexec/bin/python


# INITIALIZE NUMPY ARRAY

In [4]:
# 2 dimensional array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Initialise n*m array to all zeros

import numpy as np

np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# Arrange the number between x and y with an interval of z

import numpy as np

np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [11]:
# Print all even numbers between 10 and 20

import numpy as np

np.arange(10, 22, 2)

array([10, 12, 14, 16, 18, 20])

In [13]:
# arrange z numbers between x and y

np.linspace(10, 20, 10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [14]:
# even numbers between x and y

np.linspace(0, 10, 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [15]:
# Filling same number in n*m array

np.full((2, 3), 6)

array([[6, 6, 6],
       [6, 6, 6]])

In [20]:
# Filling random number in n*m array

np.random.random((2, 3))

array([[0.9154292 , 0.65886961, 0.81141723],
       [0.56187435, 0.02354666, 0.69601129]])

# INSPECT NUMPY ARRAY
1. Shape - retuns the dimensions/size of the array
2. Resize - use to change the shape of array

In [28]:
# Shape - retuns the dimension/size of the array and can be use to change the shape of array

arr = np.array([[1, 2, 3], [2, 3, 4]])
print(arr.shape)

arr1 = np.array([[1, 2, 3], [2, 3, 4], [4, 5, 6]])
print(arr1.shape)

(2, 3)
(3, 3)


In [32]:
# 2. Resize - use to change the shape of array

arr = np.array([[1, 2, 3], [2, 3, 4]])
arr.shape = (3, 2)
print(arr)

[[1 2]
 [3 2]
 [3 4]]


In [43]:
# Return the dimension of array

x = np.arange(24)
print(x) # prints the array

print(x.ndim) # prints the dimension of the array

rx = x.reshape(3, 2, 4) # trick : calculate factors of 24, 12, 6, 4, 3, 2, 1 and select reshape size from factors of the number
print(rx)

print(rx.ndim) # prints the dimension of the array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
3


In [52]:
# return no of elements in array

arr = np.arange(24)

print(arr.size)

ax = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(ax.size)

24
9


In [55]:
# find the data type of array

ax = np.arange(24, dtype='float')
print(ax.dtype)


float64


# Numpy Array mathematics

In [60]:
a, b = 10, 20
np.sum([a, b])

np.int64(30)

In [71]:
np.sum([[1, 2], [5, 6]]) # sums all elements

array([ 3, 11])

In [73]:
np.sum([[1, 2], [5, 6]], axis=0) # sums of x/0 axis

array([6, 8])

In [72]:
np.sum([[1, 2], [5, 6]], axis=1) # sums of y/1 axis

array([ 3, 11])

In [75]:
np.subtract(10, 20)

np.int64(-10)

In [77]:
np.multiply(10, 20)

np.int64(200)

In [78]:
np.divide(20, 10)

np.float64(2.0)

In [79]:
a = np.array([2, 4, 6])
b = np.array([1, 2, 3])

np.divide(a, b)

array([2., 2., 2.])

In [80]:
a = np.array([2, 4, 6])
b = np.array([1, 2, 3])

np.multiply(a, b)

array([ 2,  8, 18])

In [82]:
a = np.array([2, 4, 6])

np.exp(a)

array([  7.3890561 ,  54.59815003, 403.42879349])

In [83]:
a = np.array([2, 4, 6])

np.sqrt(a)

array([1.41421356, 2.        , 2.44948974])

In [84]:
a = np.array([2, 4, 6])

np.sin(a)

array([ 0.90929743, -0.7568025 , -0.2794155 ])

In [85]:
a = np.array([2, 4, 6])

np.cos(a)

array([-0.41614684, -0.65364362,  0.96017029])

In [86]:
a = np.array([2, 4, 6])

np.log(a)

array([0.69314718, 1.38629436, 1.79175947])

In [88]:
# element wise comparison

a, b = [1, 2, 3, 4], [4, 3, 2, 1]
c, d = [1, 2, 3, 4], [4, 3, 2, 1]

np.equal(a, c)

array([ True,  True,  True,  True])

In [90]:
# array wise comparison

a, b = [1, 2, 3, 4], [4, 3, 2, 1]
c, d = [1, 2, 3, 4], [4, 3, 2, 1]

np.array_equal(a, d)

False

In [103]:
a, b = [1, 2, 3, 4], [4, 3, 2, 1]
c, d = [1, 2, 3, 4], [4, 3, 2, 1]

print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.corrcoef(a))
print("Standard Deviation : ", np.std(a))

10
1
4
2.5
2.5
1.0
Standard Deviation :  1.118033988749895


# Numpy Broadcasting

In [105]:
a = np.array([[1, 2, 3, 4], [4, 3, 2, 1]])
b = np.array([[10, 11, 12, 13]])

print("First array \n ", a, "\n")
print("Second array \n ", b, "\n")
print("Broadcasted array a+b \n ", a+b, "\n")

First array 
  [[1 2 3 4]
 [4 3 2 1]] 

Second array 
  [[10 11 12 13]] 

Broadcasted array a+b 
  [[11 13 15 17]
 [14 14 14 14]] 



# array manipulation

In [106]:
a = np.array([4, 5, 6])
b = np.array([7, 8, 9])

np.concatenate((a, b))

array([4, 5, 6, 7, 8, 9])

In [108]:
# stack array row wise

a = np.array([4, 5, 6])
b = np.array([7, 8, 9])

np.vstack((a, b))


array([[4, 5, 6],
       [7, 8, 9]])

In [109]:
# stack array row wise

a = np.array([4, 5, 6])
b = np.array([7, 8, 9])

np.hstack((a, b))


array([4, 5, 6, 7, 8, 9])

In [111]:
# stack array column wise

a = np.array([4, 5, 6])
b = np.array([7, 8, 9])

np.column_stack((a, b))


array([[4, 7],
       [5, 8],
       [6, 9]])

# Splitting array

In [118]:
x = np.arange(16).reshape(4, 4)
print(x, '\n\n')

print(np.hsplit(x, 2), '\n\n')

print(np.hsplit(x, np.array([3])), '\n\n')

print(np.hsplit(x, np.array([2, 3])), '\n\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 


[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])] 


[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])] 


[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])] 


